version: '3'

services:
  api:
    build:
      context: ./
      dockerfile: DockerfileApi
    ports:
      - 16080:80
    environment:
      "ConnectionStrings:DefaultConnection": "User ID=plantLogBook;Password=plantLogBook;Server=db;Port=5433;Database=plantLogBook;Integrated Security=true;Pooling=true;"

  db:
    image: postgres
    environment:
      POSTGRES_USER: plantLogBook
      POSTGRES_PASSWORD: plantLogBook
    volumes:
      - plantLogBook-db:/var/lib/postgresql/data
    ports:
      - 5433:5432

volumes:
  plantLogBook-db: {}